import type { IconType } from "react-icons"
import {
    SiAxios,
    SiChakraui,
    SiClaude,
    SiCss,
    SiCursor,
    SiDocker,
    SiExpress,
    SiGit,
    SiGithub,
    SiGithubcopilot,
    SiGnubash,
    SiHtml5,
    SiJavascript,
    SiJsonwebtokens,
    SiMinio,
    SiMongodb,
    SiMui,
    SiMysql,
    SiNextdotjs,
    SiNodedotjs,
    SiPostgresql,
    SiPostman,
    SiPrisma,
    SiRazorpay,
    SiReact,
    SiReacthookform,
    SiReactquery,
    SiRedux,
    SiShadcnui,
    SiSqlite,
    SiStripe,
    SiTailwindcss,
    SiTurborepo,
    SiTypescript,
    SiVercel,
    SiVite,
    SiWindsurf,
    SiZod,
} from "react-icons/si"
import { TbApi, TbBrandAws, TbBrandOpenai, TbBrandVscode } from "react-icons/tb"

type TechIconEntry = {
    icon: IconType
    color?: string
}

const TECH_ICONS: Record<string, TechIconEntry> = {
    JavaScript: { icon: SiJavascript, color: "#F7DF1E" },
    TypeScript: { icon: SiTypescript, color: "#3178C6" },
    "React.js": { icon: SiReact, color: "#61DAFB" },
    React: { icon: SiReact, color: "#61DAFB" },
    "Next.js": { icon: SiNextdotjs },
    "Next.js (App Router)": { icon: SiNextdotjs },
    HTML: { icon: SiHtml5, color: "#E34F26" },
    CSS: { icon: SiCss, color: "#1572B6" },
    SQL: { icon: SiSqlite, color: "#003B57" },
    Bash: { icon: SiGnubash },
    "Tailwind CSS": { icon: SiTailwindcss, color: "#06B6D4" },
    "Shadcn UI": { icon: SiShadcnui },
    "Material UI": { icon: SiMui, color: "#007FFF" },
    "Chakra UI": { icon: SiChakraui, color: "#319795" },
    Redux: { icon: SiRedux, color: "#764ABC" },
    "React Hook Form": { icon: SiReacthookform, color: "#EC5990" },
    "Node.js": { icon: SiNodedotjs, color: "#339933" },
    Express: { icon: SiExpress },
    "REST APIs": { icon: TbApi },
    JWT: { icon: SiJsonwebtokens, color: "#000000" },
    Docker: { icon: SiDocker, color: "#2496ED" },
    MongoDB: { icon: SiMongodb, color: "#47A248" },
    PostgreSQL: { icon: SiPostgresql, color: "#4169E1" },
    Prisma: { icon: SiPrisma, color: "#2D3748" },
    MySQL: { icon: SiMysql, color: "#4479A1" },
    MinIO: { icon: SiMinio, color: "#C72E49" },
    S3: { icon: TbBrandAws, color: "#FF9900" },
    "Git & GitHub": { icon: SiGithub },
    Git: { icon: SiGit, color: "#F05032" },
    GitHub: { icon: SiGithub },
    Vite: { icon: SiVite, color: "#646CFF" },
    "React Native": { icon: SiReact, color: "#61DAFB" },
    Axios: { icon: SiAxios, color: "#5A29E4" },
    "TanStack Query": { icon: SiReactquery, color: "#FF4154" },
    Zod: { icon: SiZod, color: "#3E67B1" },
    "VS Code": { icon: TbBrandVscode, color: "#007ACC" },
    Vercel: { icon: SiVercel },
    Turborepo: { icon: SiTurborepo },
    Postman: { icon: SiPostman, color: "#FF6C37" },
    Stripe: { icon: SiStripe, color: "#635BFF" },
    Razorpay: { icon: SiRazorpay, color: "#0C2451" },
    Cursor: { icon: SiCursor },
    Claude: { icon: SiClaude, color: "#D97757" },
    "GitHub Copilot": { icon: SiGithubcopilot },
    Windsurf: { icon: SiWindsurf, color: "#0FBF9F" },
    ChatGPT: { icon: TbBrandOpenai, color: "#10A37F" },
}

export function getTechIcon(name: string): TechIconEntry | undefined {
    return TECH_ICONS[name]
}
